<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: "NotoSansKR", "DejaVu Sans", sans-serif; font-size: 11px; color: #222; padding: 30px 40px; }

.top { display: table; width: 100%; margin-bottom: 30px; }
.company { display: table-cell; width: 60%; vertical-align: top; }
.company h2 { font-size: 22px; color: #dd4814; letter-spacing: 2px; }
.company p  { font-size: 10px; color: #888; margin-top: 4px; }
.invoice-info { display: table-cell; width: 40%; text-align: right; vertical-align: top; }
.invoice-info h1 { font-size: 28px; color: #1a1a2e; font-weight: bold; letter-spacing: 3px; }
.invoice-info table { margin-left: auto; margin-top: 8px; }
.invoice-info td { padding: 2px 6px; font-size: 10px; }
.invoice-info .label { color: #999; text-align: right; }

.divider { border: none; border-top: 2px solid #dd4814; margin: 20px 0; }

.bill-to { margin-bottom: 20px; }
.bill-to h4 { font-size: 9px; text-transform: uppercase; color: #999; letter-spacing: 1px; margin-bottom: 6px; }
.bill-to p  { font-size: 12px; font-weight: bold; }

table.items { width: 100%; border-collapse: collapse; margin-top: 10px; }
table.items thead tr { background: #1a1a2e; }
table.items thead th { color: #fff; padding: 8px 12px; font-size: 10px; text-transform: uppercase; letter-spacing: .5px; }
table.items tbody td { padding: 9px 12px; border-bottom: 1px solid #eee; }
table.items tbody tr:nth-child(even) { background: #fafafa; }
.text-right { text-align: right; }

.summary { float: right; width: 40%; margin-top: 20px; }
.summary table { width: 100%; }
.summary td { padding: 5px 8px; }
.summary .s-label { color: #666; }
.summary .subtotal-row { border-top: 1px solid #eee; }
.summary .total-row td { background: #1a1a2e; color: #fff; font-size: 13px; font-weight: bold; padding: 10px 8px; }

.footer { clear: both; margin-top: 60px; padding-top: 15px; border-top: 1px solid #eee; font-size: 9px; color: #bbb; text-align: center; }
</style>
</head>
<body>

<div class="top">
    <div class="company">
        <h2>CI4 PLAYGROUND</h2>
        <p>CodeIgniter 4 Sample Application<br>
           Seoul, Republic of Korea<br>
           contact@ci4playground.dev</p>
    </div>
    <div class="invoice-info">
        <h1>INVOICE</h1>
        <table>
            <tr><td class="label">Invoice No.</td><td><strong><?= esc($invoice_no) ?></strong></td></tr>
            <tr><td class="label">Date</td><td><?= esc($date) ?></td></tr>
            <tr><td class="label">Due Date</td><td><?= esc($due_date) ?></td></tr>
        </table>
    </div>
</div>

<hr class="divider">

<div class="bill-to">
    <h4>Bill To</h4>
    <p>Sample Client Co., Ltd.</p>
    <p style="font-weight:normal;font-size:10px;color:#666;margin-top:2px;">
        123 Main Street, Seoul &bull; client@example.com
    </p>
</div>

<?php
$subtotal = array_sum(array_map(fn($i) => $i['qty'] * $i['price'], $items));
$tax      = (int)($subtotal * 0.1);
$total    = $subtotal + $tax;
?>

<table class="items">
    <thead>
        <tr>
            <th style="width:50%;text-align:left">Description</th>
            <th style="width:15%;text-align:center">Qty</th>
            <th style="width:17%;text-align:right">Unit Price</th>
            <th style="width:18%;text-align:right">Amount</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $item): ?>
    <tr>
        <td><?= esc($item['desc']) ?></td>
        <td class="text-right"><?= $item['qty'] ?></td>
        <td class="text-right">&#8361; <?= number_format($item['price']) ?></td>
        <td class="text-right">&#8361; <?= number_format($item['qty'] * $item['price']) ?></td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>

<div class="summary">
    <table>
        <tr class="subtotal-row">
            <td class="s-label">Subtotal</td>
            <td class="text-right">&#8361; <?= number_format($subtotal) ?></td>
        </tr>
        <tr>
            <td class="s-label">VAT (10%)</td>
            <td class="text-right">&#8361; <?= number_format($tax) ?></td>
        </tr>
        <tr class="total-row">
            <td>TOTAL</td>
            <td class="text-right">&#8361; <?= number_format($total) ?></td>
        </tr>
    </table>
</div>

<div class="footer">
    Thank you for your business &bull; Payment due by <?= esc($due_date) ?><br>
    Generated by CI4 Playground
</div>

</body>
</html>
